name: frontend CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the latest code from your repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (optional but recommended)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Set up Node.js (use the specified Node.js version)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      # Step 4: Install project dependencies (npm packages)
      - name: Install dependencies
        run: npm install

      # Step 5: Build a Docker image for your application
      - name: Build Docker image
        run: |
          # Build a Docker image with the specified tag
          docker build -t my-app-image .

          # Log in to Docker Hub using the provided access token
          docker login -u moislam -p ${{ secrets.DOCKER_ACCESS_TOKEN }}

          # Tag the image with a repository name and the "latest" tag
          docker tag my-app-image:latest moislam/frontend-angular-repository:latest

          # Push the Docker image to Docker Hub
          docker push moislam/frontend-angular-repository:latest



# End of the workflow
