name: frontend cd to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "moislam-webdev"
          git config --global user.email "moislam-webdev@users.noreply.github.com"
          git checkout gh-pages
          git pull
          mv -f dist/front_endemployeemanagerapp/* .
          git add .
          git commit -m "Auto-deployed from main branch"
          git push "https://${ACTIONS_TOKEN}@github.com/moislam-webdev/EmployeeManager-Frontend" gh-pages --force
